### ISSUE TITLE
Please change product name (omit PRO)

### ISSUE THREAD

**Issue by edy555** [flyoob/NanoVNA-F#1]
Hi, I'm an original developer of NanoVNA. I looked over codes you published to GitHub. Your improvement is excellent and porting onto freertos is essential I think.
Well, when I saw your repository name, I feel it is no good that named as PRO.
I think your improvement is great but it should not be named as better than others.
I propose that your product should be named such like NanoVNA-F (suffixed from your name) or something else.
I wish you to think about this issue seriously.

**Comment by flyoob** [comment]
Well, I will changed to NanoVNA-F. 3q
