### ISSUE TITLE
Update to 0.5.0 release

### ISSUE THREAD

**Issue by Constantin07** [flyoob/NanoVNA-F#6]
Hi,

Are the any plans to update firmware to 0.5.0 release based on  https://github.com/ttrftech/NanoVNA/releases ?

Thanks.

PS: Great work and good product by the way.

**Comment by flyoob** [comment]
> Are the any plans to update firmware to 0.5.0 release based on

We prioritize bug fixes, and new features released by edy555 will gradually follow up, please be patient ~
