### ISSUE TITLE
Informational commands on the serial port: "version" and "info"

### ISSUE THREAD

**Issue by mihtjel** [flyoob/NanoVNA-F#8]
Hello,
for NanoVNA-Saver, it would be a help if the following were implemented in the NanoVNA-F firmware:

1) A "version" command, returning something like, for example: "NanoVNA-F version 0.0.5"
Having the version number clearly separated by spaces from the rest of the string is an advantage for my current parsing method. ;-)

2) An "info" command, returning at least the string "NanoVNA-F" (in order to recognize the device), but preferably also for example the supported frequency span, and any additional features supported by the firmware revision. Should you include a "raw scan" command at some point, that could be noted there, for example.  This would allow the software to distinguish not just which functions are available, but also which versions of the functions, should they change over time in an incompatible manner.

Thank you for your support in developing NanoVNA-Saver! I am testing it out with the NanoVNA-F right now! :-)

**Comment by flyoob** [comment]
> Hello,
> for NanoVNA-Saver, it would be a help if the following were implemented in the NanoVNA-F firmware:
> 
> 1. A "version" command, returning something like, for example: "NanoVNA-F version 0.0.5"
>    Having the version number clearly separated by spaces from the rest of the string is an advantage for my current parsing method. ;-)
> 2. An "info" command, returning at least the string "NanoVNA-F" (in order to recognize the device), but preferably also for example the supported frequency span, and any additional features supported by the firmware revision. Should you include a "raw scan" command at some point, that could be noted there, for example.  This would allow the software to distinguish not just which functions are available, but also which versions of the functions, should they change over time in an incompatible manner.
> 
> Thank you for your support in developing NanoVNA-Saver! I am testing it out with the NanoVNA-F right now! :-)

OK, I will add these commands in the next firmware update.
Have fun with your -F machine ~ :-)
